translations = {
	mensaje_bienvenida: 'Loading application SIACE',

	abreviado: 'Abbreviated',
	abreviado_abrev: 'Abbrev.',
	accesos: 'Access',
	accesos_usuario: 'User Access',
	aceptar: 'Accept',
	actividades: 'Activities',
	adjuntar_archivo: 'Attach File',
	adjunto: 'Attached',
	administracion: 'Administration',
	agregar: 'Add',
	agregar_actividad: 'Agregar Actividad',
	agregar_coeficiente: 'Add Coefficient',
	agregar_insumo: 'Add Input',
	agregar_servicio: 'Agregar Servicio',
	agregar_item: 'Add Item',
	almacen: 'Store',
	almacenes: 'Stores',
	anexo: 'Annex',
	anular: 'Annular',
	año: 'Year',
	año_fabricacion_abrev: 'Manuf. Year',
	apellido_paterno: 'Last Name',
	apellido_materno: 'Maternal S.',
	apellidos_y_nombres: 'Surnames and Names',
	archivo: 'File',
	area: 'Area',
	asunto: 'Asunto',
	ayuda: 'Help',
	banco: 'Bank',
    buscar: 'Search',
    buscar_mercancia: 'Search Merchandise',
    caja_chica: 'Petty Cash',
	cancelar: 'Cancel',
	cantidad: 'Quantity',
	cantidad_abrev: 'Quant.',
	cargando: 'Loading',
	carroceria: 'Bodywork',
	categoria: 'Category',
	categoria_abrev: 'Cat.',
	cerrar_sesion: 'Logout',
	cese: 'Cessation',
	chasis: 'Chassis',
	clase: 'Class',
	clasificador: 'Classifier',
	clave: 'Password',
	cliente: 'Customer',
	codigo: 'Code',
	codigo_usuario: 'User Code',
	coeficiente: 'Coefficient',
	_color: 'Color',
	combustible: 'Fuel',
	comentario: 'Comment',
	compra: 'Buy',
	comprobante: 'Voucher',
	concepto: 'Concept',
	conductor: 'Conductor',
	confirmar: 'Confirm',
	consulta: 'Consultation',
	contabilidad: 'Accounting',
	contable: 'Accountant',
	contenedor: 'Container',
	cuenta: 'Account',
	cuenta_bancaria: 'Cuenta Bancaria',
	cuenta_bancaria_abrev: 'Cta. Bancaria',	
	cuenta_contable: 'Ledger Account',
	datos_principales: 'Main Data',
	datos_complementarios: 'Additional Information',
	debe: 'Should',
	declaracion_ingreso: 'Statement of Income',
	departamento: 'Department',
	descripcion: 'Description',
	descripcion_insumo: 'Input Description',
	descripcion_mercancia: 'Description of Goods',
    deshacer: 'Undo',
    destino: 'Destination',
    destino_abrev: 'Dest.',
    detalle_venta: 'Detail Sale',
	direccion: 'Address',
    distrito: 'District',
    documento: 'Document',
    documento_abrev: 'Doc.',
    documentos: 'Documents',
    documento_identidad: 'Identity Document',
    documento_identidad_abrev: 'Identity Doc.',
    documento_identidad_siglas: 'I.D.',
    documento_internacional: 'internat. Doc.',
    domicilio_fiscal: 'Fiscal Address',
    egreso: 'Egress',
    eliminar: 'Delete',
    emitir_factura: 'Issue Invoices',
    entidad_bancaria: 'Financial Institution',
    entidad_bancaria_abrev: 'Financial I.',
    especifica: 'Specifies',
    estado_civil: 'M. Estatus',
    excluir: 'Exclude',
    exportador: 'Exporter',
    e_mail: 'E-mail',
    factor: 'Factor',
    familia: 'Family',
    familia_abrev: 'Fam.',    
    fecha: 'Date',
    fecha_final: 'End Date',
    fecha_inicial: 'Start Date',    
    fecha_nacimiento: 'Date of Birth',
    fecha_registro: 'Registration Date',
    filtrar_por: 'Filter by',
    flete: 'Freight',
    foto: 'Photo',
    fotografia: 'Photography',
    fuente_financiamiento: 'Funding Source',
    fuente_financiamiento_abrev: 'Fun. Sour.',
    fuente_financiamiento_siglas: 'F.S.',
    grupo: 'Group',
    guardar: 'Save',
    haber: 'Have',
    hora: 'Time',
	igv: 'General Sales Tax',
    igv_siglas: 'I.G.V.',
    importador: 'Importer',
    importe: 'Amount',
    imprimir: 'Printer',
    informe: 'Report',
    informes_produccion: 'Production Reports',
    informes_produccion_siglas: 'P.R.',
    ingresar: 'Sign in',
    ingreso: 'Entry',
    ingresos: 'Income',
    inicio: 'Home',
    insumos_opcionales: 'Optional Inputs',
    item: 'Item',
    items: 'Items',
    latitud: 'Latitude',
    logistica: 'Logistics',
    longitud: 'Length',
    lote: 'Batch',
    lotes: 'Batches',
    lugar: 'Place',
    lugar_nacimiento: 'Place of birth',
    mantenimiento: 'Maintenance',
    maquinaria: 'Machinery',
    marca: 'Brand',
    mensaje: 'Message',
    menu: 'Menu',
    mes: 'Month',
    modelo: 'Model',
    modificar: 'Modify',
    moneda: 'Currency',
    moneda_abrev: 'Cu',
    motor: 'Motor',
    movimientos: 'Movements',
    nombre: 'Name',
    nombre_comercial: 'Trade Name',
    nivel: 'Level',
	nuevo: 'New',
	numero: 'Number',
	numero_cuenta_bancaria: 'Bank Account Number',
	operaciones: 'Operations',
	operador: 'Operator',
	otros: 'Others',
	pagina_web: 'Web page',
	pago: 'Payment',
	pais: 'Country',
	pais_origen: 'Origin Country',
	partida: 'Departure',
	partida_arancelaria: 'Tariff Item',
	partida_arancelaria_abrev: 'Tariff Item',
	persona: 'Person',
	peso: 'Weight',
	placa: 'Plate',
	porcentaje: 'Percentage',
	precio_unitario_abrev: 'Unit Price',
	presupuesto: 'Budget',
	procedencia: 'Provenance',
	procedencia_abrev: 'Prov.',
	procesos: 'Procesos',
	producto: 'Product',
	propietario: 'Owner',
	proveedor: 'Provider',
	provincia: 'Province',
	quitar: 'Remove',
	quitar_actividad: 'Quitar Actividad',
	quitar_coeficiente: 'Remove Coefficient',
	quitar_insumo: 'Remove Input',
	quitar_item: 'Remove Item',
	quitar_servicio: 'Quitar Servicio',
	razon_social: 'Busin. Name',
	rechazar: 'Reject',
	registro: 'Record',
	registro_aduanero: 'Customs Register',
	registro_compra: 'Purchase Record',
	registro_venta: 'Sales Registration',
	registros_aduana: 'Custom Records',
	registros_aduana_siglas: 'C.R.',
	remolque: 'Trailer',
	reporte: 'Report',
	reportes: 'Reports',
	reportes_accounting_libro_diario: 'Reports Account Books',
	reportes_accounting_plan_contable: 'Reports Accounting Accounts',
	reportes_treasury_comprobantes_ingreso: 'Reportes Comprobantes de Ingreso',
	reportes_treasury_contratos: 'Reports Contracts',
	reportes_treasury_cuentas_bancarias: 'Bank Accounts Reports',
	reportes_treasury_ventas: 'Sales Reports',
	reportes_treasury_comprobantes_ingreso: 'Reports Vouchers of Income',	
	requerimiento: 'Request',
	saldo: 'Balance',
	salida: 'Output',
	salidas: 'Outputs',
	salir: 'Get out',
	seguro: 'Insurance',
	serie: 'Series',
	servicio: 'Service',
	servicios: 'Services',
	sexo: 'Sex',
	sistema: 'System',
	sub_diario: 'Sub Diario',
	sub_producto: 'Sub-Product',
	subir_archivo: 'Upload File',
	tareas_presupuestales: 'Budget Tasks',
	tesoreria: 'Treasury',
	tipo: 'Type',
	tipo_contenedor: 'Container Type',
	tipo_cuenta: 'Account Type',
	tipo_cuenta_abrev: 'AccTyp',
	tipo_cuenta_bancaria: 'Bank Account Type',
	tipo_cuenta_bancaria_siglas: 'BAT'	
	tipo_pago: 'Payment Type',
	tipo_pago_siglas: 'P.T.',
	tipo_registro: 'Record Type',
	tipo_vehiculo: 'Vehicle Type',
	total: 'Total',
	tracto: 'Tract',
	transmision: 'Transmission',
	transportista: 'Haulier',
	unidad: 'Unit',
	unidad_medida: 'Measured Unit',
	unidad_medida_siglas: 'M.U.',
	usuario: 'User',
	valida_titulo: 'Validating data',
	valida_mensaje01: 'Sending data to the server, wait a moment please...',
	vehiculo: 'Vehicle',
	venta: 'Sale',

	//Menus
	menu1 : 'Security',
	menu11 : 'Groups and Permissions',
	menu12 : 'Users',
	menu13 : 'Profile',

	// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	mensaje_esperar: 'Please wait a moment...',
	mensaje_pregunta_anular: 'Is this you.  A N N U L A R  sure the selected record?',
	mensaje_pregunta_guardar: 'Is this you. Insurance  S A V E  the edited information?',
	mensaje_pregunta_eliminar: 'Is this you. Sure to  D E L E T E  the selected record?',
	mensaje_pregunta_vobo: 'Is this you. VoBo sure to assign the selected record?',
	mensaje_pregunta_vobo_deshacer: 'Is this you. VoBo sure to undo the selected record?',
	mensaje_validando_espere: 'Validating information... please wait a moment...',

	// +++ MENUS DEL SISTEMA ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	menu_admin: 'System administration',
	tipos_vehiculo: 'Types of Vehicles',
	aduanas: 'customs',

	// +++ COMPONENTES EXTJS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	pagingtoolbar_displayMsg: 'Displaying records {0} - {1} of {2}',
	pagingtoolbar_emptyMsg: 'No record found',

	// +++ FORMULARIOS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	access_login_title: 'System Access',

	accounting_libro_diariobrowse_menu: 'Daybook',
	accounting_plan_contablebrowse_menu: 'Accounting Plan',

	budget_iyueffbrowse_menu: 'Income x Source Financing',
	budget_iyueffedbrowse_menu: 'Income x Classifier',
	budget_certificadosbrowse_menu: 'Certifications',
	budget_eyuetffedbrowse_menu: 'Expenses x Classifier',
	budget_metasbrowse_menu: 'Metas',
	budget_notas_modifbrowse_menu: 'Notas Modificatorias',
	budget_tareasbrowse_menu: 'Tareas',

	ligistics_pedidosbrowse_menu: 'Requerimientos',

	operations_actividadessearch_title: 'Búsqueda de Actividad',
	operations_almacenesbrowse_menu: 'User registry',

	operations_guiasbrowse_menu: 'Entrance Tickets CETICOS',
	operations_guiasedit_title_modify: 'Ticket Entry Modify CETICOS',
	operations_guiasedit_title_new: 'New Ticket Entry CETICOS',
	operations_guiasedit_title_query: 'Ticket Entry Consultation CETICOS',
	operations_guiasedit_panel1_title: 'Vehicle Registration',
	operations_guiasedit_panel2_title: 'Customs Records',
	operations_guiasedit_panel3_title: 'CETICOS',

	operations_industriasbrowse_menu: 'Input-Output Table',
	operations_industriasedit_cip_nro : 'I.O.T. N°',
	operations_industriasedit_title_buscar_insumo: 'Seek Input',
	operations_industriasedit_title_buscar_producto: 'Product Search',	
	operations_industriasedit_title_modify: 'Modify Input-Output Table (I.O.T.)',
	operations_industriasedit_title_new: 'New Input-Output Table (I.O.T)',
	operations_industriasedit_title_query: 'Consultation Input-Output Table (I.O.T.)',

	operations_industrias_coeficientesadd_title: 'Add Coefficient',

	operations_ingresosbrowse_menu: 'Income Statements',
	operations_ingresosreport_menu: 'Revenue Merchandise',
	operations_ingresossearch_title: 'Búsqueda Declaración de Ingreso',

	operations_ingresos_comprasbrowse_menu: 'Purchases Merchandise',

	operations_lotesbrowse_menu: 'Batch Register',

	operations_packingsbrowse_menu: 'Packing List',
	operations_packingsedit_title_modify: 'Modify Packing List',
	operations_packingsedit_title_new: 'New Packing List',
	operations_packingsedit_title_query: 'Consultation Packing List',
	operations_packingsedit_title_vobo: 'Vobo Packing List Items',
	
	operations_palletsedit_title_add: 'Add Pallet',

	operations_pedidosbrowse_menu: 'Service Sheets',
	operations_pedidosedit_title_new: 'New Service Sheets',

	operations_produccionesbrowse_menu: 'Production Reports',
	operations_produccionesedit_cip_nro: 'I.O.T. N°',
	operations_produccionesedit_grid_header_descripcion_producto: 'Product Description',
	operations_produccionesedit_title_new: 'New Production Report',

	operations_registros_aduanasbrowse_menu: 'Customs Records',
	operations_registros_aduanasedit_title_new: 'Register New Customs',
	operations_registros_aduanasedit_title_modify: 'Customs Modify Registry',
	operations_registros_aduanasedit_title_modify: 'Customs Consultation Register',
	operations_registros_aduanassearchtoadd_title: 'Customs Register Search',

	operations_registros_internacionalesbrowse_menu: 'International Transport',
	operations_registros_internacionalesedit_title_new: 'New Registration International Transport',
	operations_registros_internacionalesedit_title_modify: 'Registration Modification International Transport',
	operations_registros_internacionalesedit_title_query: 'Consultation Registration International Transport',

	operations_stockreports_menu: 'Stock Reports',

	operations_salidasbrowse_menu: 'Output Statements',
	operations_salidasedit_title_new: 'New Declaration Out',
	operations_salidasreport_menu: 'Outputs Merchandise',
	operations_salidassearch_title: 'Search Out Declaration',

	pdf_operations_almacenes_report_stock_title: 'Stock Report',
	pdf_operations_guias_printer_title: 'Income Ticket',
	pdf_operations_industrias_printer_title: 'I.O.T.',
	pdf_operations_ingresos_printer_title: 'Income Statement',
	pdf_operations_producciones_printer_title: 'Production Report',
	pdf_operations_salidas_printer_title: 'Exit Declaration',

	public_aduanasbrowse_menu: 'Customs',

	public_areasbrowse_menu: 'Organic Units',

	public_bienes_servsbrowse_menu: 'Catalog of Goods and Services',
	public_bienes_servsedit_title_new: 'New Good or Service',
	public_bienes_servsedit_title_modify: 'Modify Good or Service',
	public_bienes_servsedit_title_consulta: 'Consultation Good or Service',	
	public_bienes_servsreport_menu: 'Stock of Merchandise',
	public_bienes_servsssearch_: 'Búsqueda de Mercancia / Servicio',

	public_bienes_servs_clasesbrowse_menu: 'Classes Goods / Services',

	public_contenedoresbrowse_menu: 'Containers',
	public_contenedoresedit_title_new: 'New Container',
	public_contenedoressearch_title: 'Search Container',

	public_individuosbrowse_menu: 'Identity Records',
	public_individuosedit_title_new: 'New Identity Register',
	public_individuosedit_title_modify: 'Changing Identity Register',
	public_individuosedit_title_consulta: 'Consulta Registro de Identidad',
	public_individuosedit_msg_falta_dni: 'Please state the number of Identity',
	public_individuossearch_title: 'Search for person',

	public_marcasbrowse_menu: 'Trademark',

	public_nandinasbrowse_menu: 'Tariff Items',
	public_nandinassearch_title: 'Tariff Item Search',

	public_personasbrowse_menu: 'Register Suppliers / Customers',
	public_personasedit_title_new: 'New Customer / Supplier',
	public_personasedit_title_modify: 'Modify Customer / Supplier',
	public_personasedit_title_query: 'Consultation Identity Register',
	public_personasedit_msg_falta_ruc: 'Please state the number of Record',
	public_personassearch_title: 'Search Supplier/Customer',
	public_personassearch_title_cliente: 'Search Customer',
	public_personassearch_title_proveedor: 'Search Supplier',
	public_personas_exportadoressearch_title: 'Exporter Search',
	public_personas_importadoressearch_title: 'Operator Search',
	public_personas_transportistasedit_title_new: 'New Carrier Registration',
	public_personas_transportistassearch_title: 'Search Haulier',

	public_tipos_vehiculobrowse_menu: 'Types of Vehicles',

	public_tipos_cambiobrowse_menu: 'Exchange Rate',
	public_tipos_cambioedit_new: 'New Exchange Rate',
	public_tipos_cambioedit_modify: 'Exchange Rate Modify',

	public_vehiculosbrowse_menu: 'Vehicles',
	public_vehiculosedit_title_new: 'New Vehicle',
	public_vehiculosedit_title_modify: 'Change data Vehicle',
	public_vehiculosedit_title_query: 'Vehicle Consultation',
	public_vehiculosedit_panel1_title: 'Main Data',
	public_vehiculosedit_panel2_title: 'Additional Information',
	public_vehiculossearch_title: 'Vehicle Search',
	public_vehiculossearch_titleT: 'Search Tract',

	public_usuariosbrowse_menu: 'User Registration',
	public_usuariosedit_title_new: 'New User',
	public_usuariosedit_title_modify: 'Modifying User',
	public_usuariosedit_title_query: 'User Consultation',	
	public_usuariospsw2_title: 'Key Validation',
	public_usuariospsw2_message07: 'It will  ELIMINATE  the selected document, for safety must type your password validation',
	public_usuariospsw2_message10: 'It will  ANNULAR  the selected document, for safety must type your password validation',
	public_usuariospsw2_message41: 'It will give the  VoBo  the selected document, for safety must type your password validation',
	public_usuariospsw2_message42: 'It will undo the VOBO the selected document, for safety must type your password validation',
	public_usuariospsw2_message_reject_item: 'It will REJECT the selected item, for safety must type your password validation',

	public_usuarios_accesoswindow_title: 'Access by User',
	public_usuarios_accesosedit_title_new: 'New User Access',
	public_usuarios_accesosedit_title_modify: 'Modify User Access',
	public_usuarios_accesosedit_title_query: 'Consultation User Access',

	public_usuarios_accesos_menus_opcionesbrow_title: 'Persmisos according Access Menu',

	treasury_bienes_servsbrowse_menu: 'Services CETICOS',
	treasury_bienes_servsssearch_title: 'Search Service',
	treasury_bienes_servsssearch_title_cu: 'Search Service: Use Assignment Contract',
	
	treasury_comprobantesbrowse_menu: 'Vouchers',
	treasury_comprobantesedit_title_new: 'New Voucher',
	treasury_comprobantesedit_title_modify: 'Modify voucher',
	treasury_comprobantesedit_title_query: 'Consultation Voucher',

	treasury_conceptosbrowse_menu: 'Income Concepts',
	treasury_conceptosedit_title_new: 'New Concept of Income',
	treasury_conceptosedit_title_modify: 'Income modify Concept',
	treasury_conceptosedit_title_query: 'Income Consultation Concept',

	treasury_contratosbrowse_menu: 'Contracts',
	treasury_contratosedit_title_new: 'New Contract',
	treasury_contratosedit_title_modify: 'Modify Contract',
	treasury_contratosedit_title_query: 'Consultation Contract',

	treasury_cuentas_bancariasbrowse_menu: 'Bank Accounts',
	treasury_cuentas_bancariasedit_title_new: 'New Bank Account',
	treasury_cuentas_bancariasedit_title_modify: 'Modify Bank Accounts',
	treasury_cuentas_bancariasedit_title_query: 'Consultation Bank Account',

	treasury_cuentas_bancarias_movimientosbrow_title: 'Movimentos Bancários',

	treasury_entidades_bancarias_chequesbrowse_menu: 'Check Register',

	treasury_planilla_viaticosbrowse_menu: 'Planilla de Viáticos',
	treasury_planilla_viaticosedit_title_new: 'Nuevo Planilla de Viáticos',

	treasury_recibosbrowse_menu: 'Receipt',
	treasury_recibosedit_title_new: 'Nuevo Recibo',
	treasury_recibosedit_title_query: 'Consulta de Recibo',

	treasury_ventasbrowse_menu: 'Sales Record',
	treasury_ventasedit_title_new: 'New Record Sales',
	treasury_ventasedit_title_modify: 'Modificar Registro de Ventas',
	treasury_ventasedit_title_query: 'Consultation Sales Record',
	treasury_ventassearch_title: 'Search Sales Record',
	treasury_ventassearchxcharge_title: 'Sales record Receivable',

	toolbar_capslocktooltip_title: 'Caps Lock is On',
	toolbar_capslocktooltip_msg1:  'Having Caps Lock enabled may cause you to enter your password incorrectly',
	toolbar_capslocktooltip_msg2: 'It is recommended to press Caps Lock to turn it off before typing your password.',

	util_sessionmonitor_title: 'Session Timeout Warning',
	util_sessionmonitor_buttonContinuar: 'Continue Working',
	util_sessionmonitor_buttonLogout: 'Logout',
	util_sessionmonitor_msje01: 'Your session will automatically expires after 10 minutes of  inactivity. If your session expires, any unsaved data will be lost and  you will be automatically logged out.',
	util_sessionmonitor_msje02: 'If you want  to continue working, click the "Continue Working" button',
	util_sessionmonitor_msje02: 'Your session will expire in ',
	util_sessionmonitor_msje04: ' second',
}