translations = {
	mensaje_bienvenida: 'SIACE Carregando aplicação',

	abreviado: 'Abbreviated',
	abreviado_abrev: 'Abbrev.',
	accesos: 'Acceso',
	accesos_usuario: 'Acesso do Usuário',
	aceptar: 'Aceitar',
	actividades: 'Atividades',
	adjuntar_archivo: 'Anexar Arquivo',
	adjunto: 'Ligado',
	administracion: 'Administração',
	agregar: 'Adicionar',
	agregar_actividad: 'Agregar Actividad',
	agregar_coeficiente: 'Adicionar Coeficiente',
	agregar_insumo: 'Adicionar Entrada',
	agregar_item: 'adicionar Item',
	agregar_servicio: 'Agregar Servicio',
	almacen: 'Loja',
	almacenes: 'Lojas',
	anexo: 'Anexo',
	anular: 'Anular',
	año: 'Año',
	año_fabricacion_abrev: 'Ano de Fab.',
	apellido_paterno: 'Sobrenomb.',
	apellido_materno: 'N. Solteira',
	apellidos_y_nombres: 'Sobrenomes e Nomes',
	archivo: 'Arquivo',
	area: 'Area',
	asunto: 'Asunto',
	ayuda: 'Socorro',
	banco: 'Banco',
    buscar: 'Procurar',
    buscar_mercancia: 'Encontrar Bens',
    caja_chica: 'Caixa Pequena',
	cancelar: 'Cancel',
	cantidad: 'Quantidade',
	cantidad_abrev: 'Quant.',
	cargando: 'Carregamento',
	carroceria: 'Carroçaria',
	categoria: 'Categoria',
	categoria_abrev: 'Cat.',
	cerrar_sesion: 'Logout',
	cese: 'Cessação',
	chasis: 'Chassis',
	clase: 'Classe',
	clasificador: 'Classificador',
	clave: 'Senha',
	cliente: 'Cliente',
	codigo: 'Código',
	codigo_usuario: 'Código Usuário',
	coeficiente: 'Coeficiente',
	_color: 'Cor',
	combustible: 'Combustível',
	comentario: 'Comentário',
	compra: 'Compra',
	comprobante: 'Comprovante',
	concepto: 'Conceito',
	conductor: 'Condutor',
	confirmar: 'Confirmar',
	consulta: 'Consulta',
	contabilidad: 'Contabilidade',
	contable: 'Contábil',
	contenedor: 'Contêiner',
	cuenta: 'Conta',
	cuenta_bancaria: 'Cuenta Bancaria',
	cuenta_bancaria_abrev: 'Cta. Bancaria',		
	cuenta_contable: 'Conta Contábil',
	datos_principales: 'De Dados Principal',
	datos_complementarios: 'Informações Adicionais',
	debe: 'Deveria',
	declaracion_ingreso: 'Demonstração de Resultado',
	departamento: 'Departamento',
	descripcion: 'Descrição',
	descripcion_insumo: 'Descrição de Entrada',
	descripcion_mercancia: 'Descrição dos Bens',
    deshacer: 'Desfazer',
    destino: 'Destino',
    destino_abrev: 'Dest.',
    detalle_venta: 'Detalhe Venda',
    direccion: 'Endereço',
    distrito: 'Distrito',
    documento: 'Documento',
    documento_abrev: 'Doc.',
    documentos: 'Documentos',
    documento_identidad: 'Documento Identidade',
    documento_identidad_abrev: 'Doc. Ident.',
    documento_identidad_siglas: 'D.I.',
    documento_internacional: 'Doc. Internac.',
    domicilio_fiscal: 'Endereço Fiscal',
    egreso: 'Egresso',
    eliminar: 'Tirar',
    emitir_factura: 'Emitir Facturas',
    entidad_bancaria: 'Instituição Financeira',
    entidad_bancaria_abrev: 'I. Financeira',
    especifica: 'Específico',
    estado_civil: 'E. Civil',
    excluir: 'Excluir',
    exportador: 'Exportador',
    e_mail: 'E-mail',
	factor: 'Fator',
    familia: 'Família',
    familia_abrev: 'Fam.',
    fecha: 'Data',
    fecha_final: 'Data Final',
    fecha_inicial: 'Data de Início',
    fecha_nacimiento: 'Data Nasc.',
    fecha_registro: 'Data de Registro',
    filtrar_por: 'Filtrar por',
    flete: 'Frete',
    foto: 'Foto',
    fotografia: 'Fotografia',
    fuente_financiamiento: 'Fonte de Financiamento',
    fuente_financiamiento_abrev: 'Fon. Fin.',
    fuente_financiamiento_siglas: 'F.F.',
	grupo: 'Grupo',
    guardar: 'Salvar',
	igv: 'Geral Imposto sobre Vendas',
    igv_siglas: 'I.G.V.',
    haber: 'Ter',
    hora: 'Hora',
    importador: 'Importador',
    importe: 'Valor',
    imprimir: 'Imprimir',
    informe: 'Relatório',
    informes_produccion: 'Relatórios da Produção',
    informes_produccion_siglas: 'R.P.',
    ingresar: 'Assinar em',
    ingreso: 'Entrada',
    ingresos: 'Renda',
    inicio: 'Iniciação',
    insumos_opcionales: 'Entradas Opcionais',
    item: 'Item',
    items: 'Itens',
    latitud: 'Latitude',
    longitud: 'Comprimento',    
    lotes: 'Fornada',
    lugar: 'Lugar',
    lugar_nacimiento: 'Naturalidade',
    mantenimiento: 'Manutenção',
    maquinaria: 'Maquinaria',
    marca: 'Marca',
    mensaje: 'mensagem',
    menu: 'Menu',
    mes: 'Mês',
    modelo: 'Modelo',
    modificar: 'Modificar',
    moneda: 'Moeda',
    moneda_abrev: 'Mo',
    motor: 'Motor', 
    movimientos: 'Movimientos',
    nombre: 'Nome',
    nombre_comercial: 'N. Comercial',
    nivel: 'Nível',
	nuevo: 'Novo',
	numero: 'Número',
	numero_cuenta_bancaria: 'Número Cuenta Bancaria',
	operaciones: 'Operações',
	operador: 'Operador',
	otros: 'Outros',
	pagina_web: 'Página web',
	pago: 'Pagamento',
	pais: 'País',
	pais_origen: 'País de Origem',
	partida: 'Partida',
	persona: 'Pessoa',
	peso: 'Peso',
	placa: 'Chapa',
	porcentaje: 'Percentagem',
	precio_unitario_abrev: 'P. Unitário',
	presupuesto: 'Orçamento',
	procedencia: 'Proveniência',
	procedencia_abrev: 'Prov.',
	procesos: 'Procesos',
	producto: 'Produto',
	propietario: 'Proprietário',
	proveedor: 'Provedor',
	provincia: 'Província',	
	razon_social: 'Nome Empr.',
	quitar: 'Remover',
	quitar_actividad: 'Quitar Actividad',
	quitar_coeficiente: 'Remover Coeficiente',
	quitar_insumo: 'Remover Entrada',
	quitar_item: 'Remove Item',
	quitar_servicio: 'Quitar Servicio',
	registro: 'Registro',
	rechazar: 'Rejeitar',
	registro_aduanero: 'Customs Register',
	registro_compra: 'Registro de Compra',
	registro_venta: 'Registro de Vendas',
	registros_aduana: 'Registros Aduaneiros',
	registros_aduana_siglas: 'R.A.',
	remolque: 'Trailer',
	reporte: 'Relatório',
	reportes: 'Relatórios',
	requerimiento: 'Pedido',
	saldo: 'Saldo',
	salida: 'Saída',
	salidas: 'Saídas',
	salir: 'Sair',
	seguro: 'Seguro',
	serie: 'Série',
	servicio: 'Serviço',
	servicios: 'Serviços',
	sexo: 'Sexo',
	sistema: 'Sistema',
	sub_diario: 'Sub Diario',
	sub_producto: 'Sub-Produto',
	subir_archivo: 'Upload de arquivo',
	tareas_presupuestales: 'Tarefas Orçamentais',
	tesoreria: 'Tesouraria',
	tipo: 'Tipo',
	tipo_contenedor: 'Tipo Contêiner',
	tipo_cuenta: 'Tipo Conta',
	tipo_cuenta_abrev: 'TipCon',
	tipo_cuenta_bancaria: 'Banco Tipo de Conta',
	tipo_cuenta_bancaria_siglas: 'BTC',
	tipo_pago: 'Tipo Pagamento',
	tipo_pago_siglas: 'T.P.',
	tipo_registro: 'Tipo Registro',
	tipo_vehiculo: 'Tipo Veículo',
	total: 'Total',
	tracto: 'Trato',
	transmision: 'Transmissão',
	transportista: 'Transportador',
	unidad: 'Unidade',
	unidad_medida: 'Unidade de Medida',
	unidad_medida_siglas: 'U.M.',
	usuario: 'Usuário',
	valida_titulo: 'validação de dados',
	valida_mensaje01: 'O envio de dados para o servidor, aguarde um momento por favor...',
	vehiculo: 'Veículo',
	venta: 'Venda',

	capsLockTitle: 'Caps Lock está ativada',
	capsLockMsg1: 'Se Caps lock estiver ativado, isso pode fazer com que você',
	capsLockMsg2: 'digite a senha incorretamente.',
	capsLockMsg3: 'Você deve pressionar a tecla Caps lock para desativá-la',
	capsLockMsg4: 'antes de digitar a senha.',

	// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	mensaje_esperar: 'Por favor, aguarde um momento...',
	mensaje_pregunta_anular: 'Este é você. C A N C E L A R  certeza de que o registro selecionado?',
	mensaje_pregunta_guardar: 'Este é você. S A L V A R  seguro a informação editada?',
	mensaje_pregunta_eliminar: 'Este é você. Claro que para  E X C L U I R  o registro selecionado?',
	mensaje_pregunta_vobo: 'Isso você. VoBo deixe de atribuir o registro selecionado?',
	mensaje_pregunta_vobo_deshacer: 'Este é você. VoBo ao certo para desfazer o registro selecionado?',
	mensaje_validando_espere: 'Validando informações... por favor, aguarde um momento...',

	// +++ MENUS DEL SISTEMA ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	menu_admin: 'Administração do sistema',
	tipos_vehiculo: 'Tipos de veículos',
	aduanas: 'alfândega',

	// +++ COMPONENTES EXTJS ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	pagingtoolbar_displayMsg: 'Exibindo registros {0} - {1} de {2}',
	pagingtoolbar_emptyMsg: 'Nenhum registro encontrado',

	// +++ FORMULARIOS +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	access_login_title: 'Sistema de Acesso',

	accounting_libro_diariobrowse_menu: 'Livro Diário',
	accounting_plan_contablebrowse_menu: 'Plano de Contas',

	budget_iyueffbrowse_menu: 'Ingresos x Fuente Financiamiento',
	budget_iyueffedbrowse_menu: 'Income Budget',
	budget_certificadosbrowse_menu: 'Certificaciones',
	budget_eyuetffedbrowse_menu: 'Egresos x Clasificador',
	budget_metasbrowse_menu: 'Metas',
	budget_notas_modifbrowse_menu: 'Notas Modificatorias',
	budget_tareasbrowse_menu: 'Tareas',

	ligistics_pedidosbrowse_menu: 'Requerimientos',

	operations_actividadessearch_title: 'Búsqueda de Actividad',
	operations_almacenesbrowse_menu: 'Registro do Usuário',

	operations_guiasbrowse_menu: 'Bilhetes de entrada CETICOS',
	operations_guiasedit_title_modify: 'Modificar Bilhete de Entrada CETICOS',
	operations_guiasedit_title_new: 'Novo Bilhete de Entrada CETICOS',
	operations_guiasedit_title_query: 'Consulta Bilhete de Entrada CETICOS',
	operations_guiasedit_panel1_title: 'Registro de Veículo',
	operations_guiasedit_panel2_title: 'Registros Aduaneiros',
	operations_guiasedit_panel3_title: 'CETICOS',

	operations_industriasbrowse_menu: 'Table Input-Output',
	operations_industriasedit_cip_nro : 'T.I.O. N°',
	operations_industriasedit_title_buscar_insumo: 'Solicitar a Contribuição',
	operations_industriasedit_title_buscar_producto: 'Pesquisa de Produtos',
	operations_industriasedit_title_modify: 'Modificar Table Input-Output (T.I.O.)',
	operations_industriasedit_title_new: 'New Table Input-Output (T.I.O.)',
	operations_industriasedit_title_query: 'Consulta Table Input-Output (T.I.O.)',

	operations_industrias_coeficientesadd_title: 'Adicionar Coeficiente',

	operations_ingresosbrowse_menu: 'Demonstrações de Resultados',
	operations_ingresosreport_menu: 'Receita Mercadorias',
	operations_ingresossearch_title: 'Pesquisa Declaración de Ingreso',

	operations_ingresos_comprasbrowse_menu: 'Demonstrações de Resultados',

	operations_lotesbrowse_menu: 'Registro de Lote',

	operations_packingsbrowse_menu: 'Packing List',
	operations_packingsedit_title_modify: 'Modificar Packing List',
	operations_packingsedit_title_new: 'Novo Packing List',
	operations_packingsedit_title_query: 'Consulta Packing List',
	operations_packingsedit_title_vobo: 'Vobo Items Packing List',
	
	operations_palletsedit_title_add: 'Adicionar Pallet',

	operations_pedidosbrowse_menu: 'Fichas de Serviços',
	operations_pedidosedit_title_new: 'Novo Fichas de Serviços',

	operations_produccionesbrowse_menu: 'Relatórios de Produção',
	operations_produccionesedit_cip_nro: 'T.I.O. N°',
	operations_produccionesedit_grid_header_descripcion_producto: 'Descrição do Produto',
	operations_produccionesedit_title_new: 'Novo Relatório de Produção',

	operations_registros_aduanasbrowse_menu: 'Registros Aduaneiros',
	operations_registros_aduanasedit_title_new: 'Registrar Nova Customs',
	operations_registros_aduanasedit_title_modify: 'Alteração do Registro Customs',
	operations_registros_aduanasedit_title_query: 'Alteração do Registro Customs',
	operations_registros_aduanassearchtoadd_title: 'Pesquisa Registo Aduaneira',

	operations_registros_internacionalesbrowse_menu: 'Transporte Internacional',
	operations_registros_internacionalesedit_title_new: 'Novo Cadastro de Transporte Internacional',
	operations_registros_internacionalesedit_title_modify: 'Registro Modificação Transporte Internacional',
	operations_registros_internacionalesedit_title_query: 'Registro Modificação Transporte Internacional',

	operations_salidasbrowse_menu: 'Declaração de Saída',
	operations_salidasedit_title_new: 'Declaração Nova Fora',
	operations_salidasreport_menu: 'Saídas de Mercadorias',
	operations_salidassearch_title: 'Pesquisa Declaração de Saida',

	pdf_operations_almacenes_report_stock_title: 'Relatório de Estoque',
	pdf_operations_industrias_printer_title: 'T.I.O.',
	pdf_operations_ingresos_printer_title: 'Demonstração de Resultados',
	pdf_operations_producciones_printer_title: 'Relatório de Produção',
	pdf_operations_salidas_printer_title: 'Declaração Exit',

	public_aduanasbrowse_menu: 'Alfândega',

	public_areasbrowse_menu: 'Unidades Orgânicas',

	public_bienes_servsbrowse_menu: 'Catálogo de Produtos e Serviços',
	public_bienes_servsedit_title_new: 'Novo Dem ou Serviço',
	public_bienes_servsedit_title_modify: 'Modificar Bien o Servicio',
	public_bienes_servsedit_title_consulta: 'Consulta de Bien o Servicio',	
	public_bienes_servsreport_menu: 'Stock de Mercancías',
	public_bienes_servsssearch_: 'Búsqueda de Mercancia / Servicio',

	public_bienes_servs_clasesbrowse_menu: 'Classes Produtos / Serviços',

	public_contenedoresbrowse_menu: 'Containers',
	public_contenedoresedit_title_new: 'Nova Embalagem',
	public_contenedoressearch_title: 'Pesquisa Container',

	public_individuosbrowse_menu: 'Registros de Identidade',
	public_individuosedit_title_new: 'Novo Identity Register',
	public_individuosedit_title_modify: 'Modificar Registro de Identidade',
	public_individuosedit_title_consulta: 'Consulta Registro de Identidade',
	public_individuosedit_msg_falta_dni: 'Por favor, indique o número da Carteira de Identidade',

	public_marcasbrowse_menu: 'Marca Registrada',

	public_nandinasbrowse_menu: 'Itens da Pauta',
	public_nandinassearch_title: 'Pauta do Produto Pesquisar',

	public_personasbrowse_menu: 'Registro Fornecedores / Clientes',
	public_personasedit_title_new: 'Novo fornecedor / cliente',
	public_personasedit_title_modify: 'Modificar fornecedor / cliente',
	public_personasedit_title_query: 'Provedor de Consulta / Customer',
	public_personasedit_msg_falta_ruc: 'Por favor, especifique Número de Registro',
	public_personassearch_title: 'Pesquisa Fornecedor/Cliente',
	public_personassearch_title_cliente: 'Pesquisa Cliente',
	public_personassearch_title_proveedor: 'Pesquisa Fornecedor',
	public_personas_exportadoressearch_title: 'Pesquisa Exportador',
	public_personas_importadoressearch_title: 'Pesquisa Operador',
	public_personas_transportistasedit_title_new: 'Novo Cadastro de Portador',
	public_personas_transportistassearch_title: 'Pesquisa Transportador',

	public_tipos_vehiculobrowse_menu: 'Tipos de Veículos',

	public_tipos_cambiobrowse_menu: 'Tipo Troca',

	public_vehiculosbrowse_menu: 'Veículos',
	public_vehiculosedit_title_new: 'Novo Veículo',
	public_vehiculosedit_title_modify: 'Alterar dados do Veículo',
	public_vehiculosedit_title_query: 'Consulta do Veículo',
	public_vehiculosedit_panel1_title: 'Dados Principal',
	public_vehiculosedit_panel2_title: 'Informações Adicionais',
	public_vehiculossearch_title: 'Procura de Veículos',
	public_vehiculossearch_titleT: 'Procurar Tract',

	public_usuariosbrowse_menu: 'Registo do Utilizador',
	public_usuariospsw2_title: 'Validação Key',
	public_usuariospsw2_message07: 'Ele irá  ELIMINAR  o documento selecionado, para a segurança precisa digitar a sua senha de validação',
	public_usuariospsw2_message10: 'Ele irá  ANULAR  o documento selecionado, para a segurança precisa digitar a sua senha de validação',
	public_usuariospsw2_message41: 'Ele lhe dará o VoBo o documento selecionado, para a segurança devem digitar sua senha de validação',
	public_usuariospsw2_message42: 'Ele irá desfazer a VOBO o documento selecionado, para a segurança devem digitar sua senha de validação',
	public_usuariospsw2_message_reject_item: 'Ele irá rejeitar o item selecionado, para a segurança devem digitar sua senha de validação',

	public_usuarios_accesoswindow_title: 'Acesso por Usuário',
	public_usuarios_accesosedit_title_new: 'Novo Acesso do Usuário',
	public_usuarios_accesosedit_title_modify: 'Modificar Acesso do Usuário',
	public_usuarios_accesosedit_title_query: 'Consulta de Acesso do Usuário',

	public_usuarios_accesos_menus_opcionesbrow_title: 'Persmisos segundo menu Acesso',

	treasury_bienes_servsbrowse_menu: 'Serviços CETICOS',
	treasury_bienes_servsssearch_title: 'Pesquisa Serviço',
	treasury_bienes_servsssearch_title_cu: 'Serviço de Pesquisa: Uso Contrato de Cessão',

	treasury_comprobantesbrowse_menu: 'Vouchers',
	treasury_comprobantesedit_title_new: 'Nuevo Comprobante',
	treasury_comprobantesedit_title_modify: 'Modificar Comprobante',
	treasury_comprobantesedit_title_query: 'Consulta de Comprobante',

	treasury_conceptosbrowse_menu: 'Renda Conceitos',
	treasury_conceptosedit_title_new: 'New Concept of Income',
	treasury_conceptosedit_title_modify: 'Income modify Concept',
	treasury_conceptosedit_title_query: 'Income Consultation Concept',

	treasury_contratosbrowse_menu: 'Contratos',
	treasury_contratosedit_title_new: 'Novo Contrato',
	treasury_contratosedit_title_modify: 'Modificar Contrato',
	treasury_contratosedit_title_query: 'Contrato Consulta',

	treasury_cuentas_bancariasbrowse_menu: 'Contas Bancárias',
	treasury_cuentas_bancariasedit_title_new: 'Conta Novo Banco',
	treasury_cuentas_bancariasedit_title_modify: 'Modificar Conta Bancária',
	treasury_cuentas_bancariasedit_title_query: 'Conta consulta Banco',

	treasury_cuentas_bancarias_movimientosbrow_title: 'Movimientos Bancarios',

	treasury_entidades_bancarias_chequesbrowse_menu: 'Registro de Cheques',

	treasury_planilla_viaticosbrowse_menu: 'Planilla de Viáticos',
	treasury_planilla_viaticosedit_title_new: 'Nuevo Planilla de Viáticos',

	treasury_recibosbrowse_menu: 'Receipt',
	treasury_recibosedit_title_new: 'Nuevo Recibo',
	treasury_recibosedit_title_query: 'Consulta de Recibo',	

	treasury_ventasbrowse_menu: 'Registro de Vendas',
	treasury_ventasedit_title_new: 'Vendas Novo Record',
	treasury_ventasedit_title_modify: 'Modificar Registro de Ventas',
	treasury_ventasedit_title_query: 'Registro de consulta Vendas',
	treasury_ventassearch_title: 'Registro da Pesquisa Vendas',
	treasury_ventassearchxcharge_title: 'Registro de Ventas x Cobrar',

	toolbar_capslocktooltip_title: 'Caps Lock está ativado',
	toolbar_capslocktooltip_msg1:  'Tendo Caps Lock ativado pode causar a digitar sua senha incorretamente',
	toolbar_capslocktooltip_msg2: 'Recomenda-se pressione Caps Lock para desligá-lo antes de digitar sua senha.',

	util_sessionmonitor_title: 'AVISO! Tempo limite da sessão',
	util_sessionmonitor_buttonContinuar: 'Continuar a Trabalhar',
	util_sessionmonitor_buttonLogout: 'Sesion Cerrar',
	util_sessionmonitor_msje01: 'Sua sessão expira automaticamente após 10 minutos de inatividade. Se a sessão expirar, os dados não salvos serão perdidos ea sessão será iniciada automaticamente.',
	util_sessionmonitor_msje02: 'Se você quiser continuar trabalhando, clique no botão "Continuar a Trabalhar"',
	util_sessionmonitor_msje03: 'Sua sessão expirou em ',
	util_sessionmonitor_msje04: ' segundo',
}